### ISSUE TITLE
This needs some documentation

### ISSUE THREAD

**Issue by robbestad** [geoffb/ahi#1]
How do you even get going here? :)

**Comment by geoffb** [comment]
You read my mind, of course!

In seriousness, this engine is an experiment that I work on here and there. I'm not sure it's stable enough for documentation yet. That said, I could whip up a quick guide on the basics.

**Comment by robbestad** [comment]
Ahh, but not all of us has access to instant Geoffumentation, or even ESP. :) If you have the time, a quick guide would be awesome.

**Comment by geoffb** [comment]
Added some words in [README.md](https://github.com/geoffb/ahi/blob/master/README.md). Maybe it helps?

**Comment by robbestad** [comment]
Very nice :+1: That's all that's needed to get cracking I think. One note, Mac users won't be able to run ahi-tools because cli.js has \r for line endings (invalid for a unix system). These need to be converted.

**Comment by geoffb** [comment]
Good catch on the line endings. I've been working with the modules using `npm link` so I hadn't noticed. Also, it could have something to do with running `npm publish` from my Windows box. (I tend to swap back and forth from OSX to Win quite often)
